[package]
name = "minipath"
version = "0.1.0"
authors = ["Kuba Marek <blue.cube@seznam.cz>"]
description = "Toy path tracer, focused more on the toy part, than the path tracer part"
edition = "2018"

[features]
gui = ["sdl2"]

[dependencies]
euclid = "0.20.7"
image = "0.23.0"
rand = "0.7.3"
sdl2 = { version = "0.33.0", optional= true }

crossbeam-utils = "0.7.2"
num_cpus = "1.12.0"
scopeguard = "1.1.0"
parking_lot = "0.10.0"
snafu = "0.6.2"

[dev-dependencies]
proptest = "0.9.5"
panic-control = "0.1.4"
