[package]
name = "minipath"
version = "0.1.0"
authors = ["Kuba Marek <blue.cube@seznam.cz>"]
description = "Toy path tracer, focused more on the toy part, than the path tracer part"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.20.7"
anyhow = "1.0.26"
crossbeam-utils = "0.7.2"
num_cpus = "1.12.0"
image = "0.23.0"
sdl2 = "0.33.0"
rand = "0.7.3"

[dev-dependencies]
proptest = "0.9.5"
