[package]
name = "minipath"
version = "0.1.0"
authors = ["Kuba Marek <blue.cube@seznam.cz>"]
description = "Toy path tracer, focused more on the toy part, than the path tracer part"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
proptest = "0.9.5"

[dependencies]
